openapi: 3.0.0
info:
  title: Botapeer API
  description: Botapeer API
  version: 1.0.0
servers:
  - url: http://localhost:8081/api
  - url: http://api.botapeer.com/api
paths:
  '/users':
    get:
      operationId: getUsersOrGetUserByName
      tags:
        - User
      description: User一覧もしくは名前からユーザーを取得
      parameters:
        - in: query
          name: username
          description: ユーザー名
          required: false
          schema:
            type: string
            example: taro
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '404':
          description: 404(User Not Found)
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ErrorResponse'
        '405':
          description: 405(Validation exception)
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ErrorResponse'
          headers:
            http_status:
              description: HTTPステータス
              schema:
                type: integer
  '/users/{userId}':
    get:
      operationId: findUserById
      tags:
        - User
      description: 任意のUserを取得
      parameters:
        - in: path
          name: userId
          description: ユーザーID
          required: true
          schema:
            type: string
            example: 1
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: 404(User Not Found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '405':
          description: 405(Validation exception)
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ErrorResponse'
          headers:
            http_status:
              description: HTTPステータス
              schema:
                type: integer
    patch:
      operationId: updateUser
      tags:
        - User
      description: 任意のUserを更新
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          description: ユーザーID
          required: true
          schema:
            type: string
            example: 1
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                formData:
                  $ref: '#/components/schemas/UpdateUserFormData'
                profileImage:
                  type: string
                  format: binary
                coverImage:
                  type: string
                  format: binary
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: 401(Unauthorized)
        '405':
          description: 405(Validation exception)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers:
            http_status:
              description: HTTPステータス
              schema:
                type: integer
    delete:
      operationId: deleteUser
      tags:
        - User
      description: 任意のUserを削除
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          description: ユーザーID
          required: true
          schema:
            type: string
            example: 1
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: 401(Unauthorized)
          headers:
            http_status:
              description: HTTPステータス
              schema:
                type: integer
  '/users/plant_records/{plantRecordId}':
    get:
      operationId: findUserByPlantRecordId
      tags:
        - User
      description: 任意のUserをPlantRecordIdから取得
      parameters:
        - in: path
          name: plantRecordId
          description: 生育記録ID
          required: true
          schema:
            type: string
            example: 1
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: 404(User Not Found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/auth/signin':
    post:
      operationId: signin
      tags:
        - Auth
      description: サインイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtAuthenticationResponse'
        '404':
          description: 404(User Not Found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'                
components:
  schemas:
    UpdateUserFormData:
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 15
        email:
          type: string
          format: email
          minLength: 1
          maxLength: 255
        description:
          type: string
      required:
        - name
        - email
    User:
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 15
        email:
          type: string
          format: email
        status:
          type: integer
        description:
          type: string
        profileImage:
          type: string
        coverImage:
          type: string
      required:
        - name
        - email
    SignInRequest:
      properties:
        usernameOrEmail:
          type: string
        password:
          type: string
      required:
        - usernameOrEmail
        - password                 
    JwtAuthenticationResponse:
      properties:
        accessToken:
          type: string
        tokenType:
          type: string
      required:
        - accessToken
        - tokenType         
    ErrorResponse:
      properties:
        errors:
          $ref: '#/components/schemas/Error'
    Error:
        type: array
        items:
          properties:
            code:
              type: integer
            message:
              type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT