/**
 * Botapeer API
 * Botapeer API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateUserFormData } from '../model/UpdateUserFormData';
import { HttpFile } from '../http/http';

export class UpdateUserRequest {
    'formData'?: UpdateUserFormData;
    'profileImage'?: HttpFile;
    'coverImage'?: HttpFile;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "formData",
            "baseName": "formData",
            "type": "UpdateUserFormData",
            "format": ""
        },
        {
            "name": "profileImage",
            "baseName": "profileImage",
            "type": "HttpFile",
            "format": "binary"
        },
        {
            "name": "coverImage",
            "baseName": "coverImage",
            "type": "HttpFile",
            "format": "binary"
        }    ];

    static getAttributeTypeMap() {
        return UpdateUserRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

