/* tslint:disable */
/* eslint-disable */
/**
 * Botapeer API
 * Botapeer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePostRequest
 */
export interface CreatePostRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePostRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostRequest
     */
    'article': string;
    /**
     * 
     * @type {File}
     * @memberof CreatePostRequest
     */
    'imageUrl': File;
}

