/* tslint:disable */
/* eslint-disable */
/**
 * Botapeer API
 * Botapeer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreatePostFormData } from './create-post-form-data';

/**
 * 
 * @export
 * @interface CreatePostRequest
 */
export interface CreatePostRequest {
    /**
     * 
     * @type {CreatePostFormData}
     * @memberof CreatePostRequest
     */
    'formData'?: CreatePostFormData;
    /**
     * 
     * @type {File}
     * @memberof CreatePostRequest
     */
    'image': File;
}

