/* tslint:disable */
/* eslint-disable */
/**
 * Botapeer API
 * Botapeer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePlantRecordRequest
 */
export interface CreatePlantRecordRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePlantRecordRequest
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePlantRecordRequest
     */
    'placeId'?: number;
}

