/* tslint:disable */
/* eslint-disable */
/**
 * Botapeer API
 * Botapeer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LikeResponse
 */
export interface LikeResponse {
    /**
     * 
     * @type {number}
     * @memberof LikeResponse
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof LikeResponse
     */
    'userId': number;
    /**
     * 
     * @type {number}
     * @memberof LikeResponse
     */
    'postId'?: number;
    /**
     * 
     * @type {string}
     * @memberof LikeResponse
     */
    'commentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LikeResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof LikeResponse
     */
    'updatedAt'?: string;
}

