/* tslint:disable */
/* eslint-disable */
/**
 * Botapeer API
 * Botapeer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PlaceResponse } from './place-response';
// May contain unused imports in some cases
// @ts-ignore
import { PostResponse } from './post-response';

/**
 * 
 * @export
 * @interface PlantRecordResponse
 */
export interface PlantRecordResponse {
    /**
     * 
     * @type {number}
     * @memberof PlantRecordResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PlantRecordResponse
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof PlantRecordResponse
     */
    'alive'?: number;
    /**
     * 
     * @type {string}
     * @memberof PlantRecordResponse
     */
    'endDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlantRecordResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlantRecordResponse
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {PlaceResponse}
     * @memberof PlantRecordResponse
     */
    'place'?: PlaceResponse;
    /**
     * 
     * @type {Array<PostResponse>}
     * @memberof PlantRecordResponse
     */
    'posts'?: Array<PostResponse>;
}

