/* tslint:disable */
/* eslint-disable */
/**
 * Botapeer API
 * Botapeer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LikeResponse } from './like-response';

/**
 * 
 * @export
 * @interface PostResponse
 */
export interface PostResponse {
    /**
     * 
     * @type {number}
     * @memberof PostResponse
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostResponse
     */
    'plantRecordId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'article'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostResponse
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<LikeResponse>}
     * @memberof PostResponse
     */
    'likes'?: Array<LikeResponse>;
}

