/* tslint:disable */
/* eslint-disable */
/**
 * Botapeer API
 * Botapeer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostResponse
 */
export interface PostResponse {
    /**
     * 
     * @type {number}
     * @memberof PostResponse
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostResponse
     */
    'plantRecordId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'article'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'image_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostResponse
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    'updated_at'?: string;
}

