name: Generate Code[Development]
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - dev
jobs:
  generate-code:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: typescriptのコード生成
        run: make generate-docker-typescript-axios-dev
      - name: JDK 11のセットアップ
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: springのコード生成
        run: make generate-docker-spring
      - name: jarファイル生成（Mavenでビルド）
        run: cd spring && mvn clean package
      - name: mavenパッケージのデプロイ
        run: cd spring && mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      - name: 生成コードのコミット
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "Generated code"
      - name: 生成コードのプッシュ
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: dev
      - run: echo "🍏 This job's status is ${{ job.status }}."